const opportunities=[
{title:"Promise Partnership",organization:"Promise Partnership",category:"Volunteer",location:"Saint John",type:"Mentoring",description:"Mentor school students and contribute to youth development.",link:"https://www.instagram.com/promisepartnership/"},
{title:"Swim with a Mission",organization:"Swim with a Mission",category:"Volunteer",location:"Saint John",type:"Youth & Water Safety",description:"Help teach young people water safety and swimming skills.",link:"https://www.instagram.com/swam.saintjohn/"},
{title:"Saint John Newcomers",organization:"Saint John Newcomers Centre",category:"Volunteer",location:"Saint John",type:"Community",description:"Support newcomers and contribute to community inclusion.",link:"https://www.instagram.com/sjnewcomerscentre/"},
{title:"PRUDE Inc.",organization:"PRUDE Inc.",category:"Volunteer",location:"Saint John",type:"Community & DEI",description:"Get involved with diversity, equity and inclusion initiatives.",link:"https://prudeinc.org/"},
{title:"Sexual Violence New Brunswick",organization:"SVNB",category:"Volunteer",location:"New Brunswick",type:"Community Support",description:"Explore volunteer opportunities and training with SVNB.",link:"https://svnb.ca/en/volunteer/"},
{title:"Horizon Health Network",organization:"Horizon Health Network",category:"Volunteer",location:"New Brunswick",type:"Healthcare",description:"Healthcare volunteering opportunities in New Brunswick. Best for students interested in healthcare.",link:"https://careers.horizonnb.ca/en/volunteering/"},
{title:"Social Pediatrics NB",organization:"Social Pediatrics NB",category:"Volunteer",location:"New Brunswick",type:"Healthcare & Community",description:"Explore opportunities to support children, youth and community health.",link:"https://www.nbsocialpediatrics.com/"},
{title:"UNB Community Volunteering Club",organization:"UNB Saint John",category:"Volunteer",location:"Saint John",type:"Fundraising & Community",description:"Fundraising and community support opportunities through the student club.",link:"https://www.instagram.com/volunteeringunbsj/"},
{title:"Saint John Cares",organization:"Saint John Cares Inc.",category:"Volunteer",location:"Saint John",type:"Community",description:"Find ways to help others and get involved in the local community.",link:"https://www.stjohnscares.org/ways-to-help-others.html"},
{title:"Volunteer Success",organization:"Volunteer Search Engine",category:"Volunteer",location:"Online",type:"Search Tool",description:"Search for volunteer opportunities using a volunteer opportunity platform.",link:"https://volunteersuccess.com/"},
{title:"Greater Saint John Volunteer Connector",organization:"Greater Saint John Volunteer Connector",category:"Volunteer",location:"Saint John",type:"Search Tool",description:"Find volunteer opportunities across Greater Saint John.",link:"https://gsjvolunteer.ca/"},
{title:"Be There Certificate",organization:"Be There Certificate",category:"Certificates",location:"Online",type:"Certificate",description:"A certificate option focused on building skills for supporting others.",link:"https://betherecertificate.org/"},
{title:"Seeds of Change",organization:"Sexual Violence New Brunswick",category:"Certificates",location:"New Brunswick",type:"Training",description:"Bystander training. The source document notes discounted or free options for UNB students.",link:"https://svnb.ca/"},
{title:"DEI Training",organization:"PRUDE Inc.",category:"Certificates",location:"Saint John",type:"Training",description:"Explore diversity, equity and inclusion training opportunities.",link:"https://prudeinc.org/"},
{title:"Courses & Learning",organization:"Curated student learning",category:"Courses",location:"Online",type:"Learning",description:"Online and local courses, learning platforms and experiences.",link:"https://www.coursera.org/"},
{title:"Jobs & Internships",organization:"Student Opportunities",category:"Jobs",location:"Canada",type:"Career",description:"Student jobs, internships and work opportunities.",link:"https://www.unb.ca/"},
{title:"Scholarships & Awards",organization:"Student Funding",category:"Scholarships",location:"Canada",type:"Funding",description:"Scholarships, awards and funding opportunities.",link:"https://www.unb.ca/"},
{title:"Leadership & Campus Opportunities",organization:"UNB Saint John",category:"Leadership",location:"Saint John",type:"Leadership",description:"Campus leadership roles, student societies and ways to get involved.",link:"https://www.unb.ca/saintjohn/"},
{title:"Career & Academic Resources",organization:"UNB",category:"Career",location:"Saint John",type:"Resource",description:"Resume, LinkedIn, academic, career and professional development resources.",link:"https://www.unb.ca/"}
];
const grid=document.getElementById("grid"),search=document.getElementById("search"),category=document.getElementById("category"),location=document.getElementById("location"),count=document.getElementById("count"),empty=document.getElementById("empty");
const icons={Volunteer:"🤝",Certificates:"📜",Courses:"🎓",Jobs:"💼",Scholarships:"🏆",Leadership:"🌱",Career:"📚"};
[...new Set(opportunities.map(o=>o.category))].sort().forEach(c=>category.add(new Option(c,c)));
[...new Set(opportunities.map(o=>o.location))].sort().forEach(l=>location.add(new Option(l,l)));
document.querySelectorAll("[data-category]").forEach(b=>b.addEventListener("click",()=>{category.value=b.dataset.category;render();document.querySelector(".opportunity-header").scrollIntoView({behavior:"smooth"});}));
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function render(){const t=search.value.trim().toLowerCase(),c=category.value,l=location.value;
const r=opportunities.filter(o=>{const s=`${o.title} ${o.organization} ${o.category} ${o.location} ${o.type} ${o.description}`.toLowerCase();return(!t||s.includes(t))&&(c==="All"||o.category===c)&&(l==="All"||o.location===l)});
grid.innerHTML="";r.forEach(o=>{const x=document.createElement("article");x.className="card";x.innerHTML=`<span class="tag">${icons[o.category]||"⭐"} ${esc(o.category)}</span><h3>${esc(o.title)}</h3><div class="org">${esc(o.organization)}</div><p>${esc(o.description)}</p><div class="meta"><span>📍 ${esc(o.location)}</span><span>✦ ${esc(o.type)}</span></div><a class="apply" href="${o.link}" target="_blank" rel="noopener">Apply / Learn More →</a>`;grid.appendChild(x)});
count.textContent=`${r.length} ${r.length===1?"opportunity":"opportunities"}`;empty.style.display=r.length?"none":"block"}
search.addEventListener("input",render);category.addEventListener("change",render);location.addEventListener("change",render);render();